### ISSUE TITLE
PVR, ETC Support

### ISSUE THREAD

**Issue by lloyar** [atteneder/KtxUnity#12]
iOS and Android not support DXT Texture

**Comment by atteneder** [comment]
Not sure what your problem was or why you closed it youself.

PVRTC and ETC should work.
DXT don't work on iOS/Android, but that's a hardware restriction, as far as I know.

**Comment by lloyar** [comment]
Previously tried to load KTX 2.0 files with PVRTC and ETC on the phone.
I did n’t realize Basis Universal was a better choice.
Thank you very much for your work, it helped me a lot.

**Comment by atteneder** [comment]
Glad to hear that, thanks!

I added more [detailed limitation description to the readme file.](https://github.com/atteneder/KtxUnity) to avoid confusion.
