### ISSUE TITLE
GUID conflicts when using this plugin together with DracoUnity

### ISSUE THREAD

**Issue by D33pTh0ught** [atteneder/KtxUnity#13]
When using both your gltf extension plugins like this
```
    "com.atteneder.draco": "https://gitlab.com/atteneder/DracoUnity.git",
    "com.atteneder.ktx": "https://gitlab.com/atteneder/ktxunity.git",
```
Unity throws a few errors like this:
```
GUID [315b0c33fa9ea48f4bf45d3f6a2646c0] for asset 'Packages/com.atteneder.ktx/Runtime/Plugins' conflicts with:
  'Packages/com.atteneder.draco/Runtime/Plugins' (current owner)
We can't assign a new GUID because the asset is in an immutable folder. The asset will be ignored.
```
Unity cannot generate new meta files because the packages in the PackageCache are immutable.

**Comment by atteneder** [comment]
thanks for the report. I noticed it as well (without major issues though), but I have to look into it.

Do you, by any chance, know whether *.meta files can be omitted/ignored by GIT for packages?

**Comment by D33pTh0ught** [comment]
> I noticed it as well (without major issues though)

It doesn't create issues in the Editor, however creating a build (e.g for Android) fails.

> Do you, by any chance, know whether *.meta files can be omitted/ignored by GIT for packages?

As far as I know they can't be omitted since Unity can't create them because they are in an immutable folder.

**Comment by atteneder** [comment]
Those should be fixed now!
