### ISSUE TITLE
Texture upside down

### ISSUE THREAD

**Issue by lloyar** [atteneder/KtxUnity#14]
Why is Basis Texture upside down?

**Comment by atteneder** [comment]
Hi,
I cannot help you without more information like concrete error description sample file and screenshots.

I noticed that textures are upside down in the inspector sometimes, but applied on materials they seem fine.

It may be that texture space definitions vary between GPU formats and engines. Maybe you hit a special case.

**Comment by lloyar** [comment]
This is really an Confusing thing.
I also found out the textures are upside down in the inspector is indeed.
Maybe I hit a special case. 😢
