### ISSUE TITLE
SampleSceneKTX crashes on iOS

### ISSUE THREAD

**Issue by daverin** [atteneder/KtxUnity#15]
### Issue

The SampleSceneBasisUniversal works perfectly, however, any loading of KTX textures fails with a `Thread 1: 
EXC_BAD_ACCESS (code=1, address=0x100000000)` on Xcode. 

Here are the final log statements from Xcode before the crash:
```
Transcode to GraphicsFormat RGBA_ASTC4X4_SRGB (ASTC_4x4_RGBA)
KtxUnity.<LoadBytesRoutine>d__0:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
KtxUnity.<LoadFile>d__8:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

Transcode to GraphicsFormat RGB_ETC_UNorm (ETC1_RGB)
KtxUnity.<LoadBytesRoutine>d__0:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
KtxUnity.<LoadFile>d__8:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

Transcode to GraphicsFormat RGB_ETC_UNorm (ETC1_RGB)
KtxUnity.<LoadBytesRoutine>d__0:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
KtxUnity.<LoadFile>d__8:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
```

### Other information

Upon doing an iOS build I received the following error from the Editor:

<img src="https://user-images.githubusercontent.com/70378377/91657431-1b8c7900-eac1-11ea-9782-e22d687c77e8.jpg" alt="Screenshot 2020-08-30 at 13 01 33" height="300"/>

In order to solve this issue I had to disable the iOS target for `Plugins/x86/ktx_unity.so`

### Build Environment

Xcode: 11.6 (11E708)
iOS: 13.6.1
Unity: 2020.1.0b10

Any ideas on how to solve this issue would be most appreciated.

**Comment by atteneder** [comment]
Thanks for reporting! Is it possible to provide a sample KTX file that leads to the crash?

KtxUnity depends on KTX-Software and currently uses an older alpha version of it. In the meantime the format header changed, so it may be possible that an update is required.

This update is planned, though I'm waiting for the final release.

**Comment by daverin** [comment]
Hi @atteneder 

My apologies. 

I thought the [KtxUnityDemo](https://github.com/atteneder/KtxUnityDemo) referenced the latest commit of this repo, but it's a GitLab repo with a similar URL. 

This issue can be closed for now.

**Comment by atteneder** [comment]
Well, KtxUnityDemo does use this repo/package internally. And KtxUnity uses native libs built from [KTX-Software](https://github.com/KhronosGroup/KTX-Software).

Hope that clarifies the relations. Feel free to provide a sample file if you need support, otherwise close the issue.

**Comment by daverin** [comment]
I understand. Probably old incompatible KTX files in the repo.

**Comment by daverin** [comment]
Hi @atteneder. I've built a KTX file with the latest KTX-Software. I want to build libktx_unity.a for iOS. I'm able to build a .dylib but not a static library. I'm new to building c++. What is the procedure for building libktx_unity.a for iOS?

**Comment by atteneder** [comment]
> Hi @atteneder. I've built a KTX file with the latest KTX-Software. I want to build libktx_unity.a for iOS. I'm able to build a .dylib but not a static library. I'm new to building c++. What is the procedure for building libktx_unity.a for iOS?

That would take me quite some time to explain. I'd rather invest that time to prepare a PR for KTX-Software myself instead soonish.

If you cannot wait, inspect the [branch](https://github.com/atteneder/KTX-Software/tree/cmake_unity_basisu) I built the current binaries from, read how the CMake configuration is done and apply it to the current master.

**Comment by daverin** [comment]
Perfect 👌🏾 Thanks for the help

**Comment by daverin** [comment]
Hi @atteneder 

I did as you suggested and I was able to successfully build libktx_unity.a for iOS and ktx_unity.bundle for Mac. However, I am still getting [this](https://github.com/atteneder/KtxUnity/issues/15#issue-688699965) error.

Unity Editor: `Transcoding failed!` 
iOS `Thread 1: EXC_BAD_ACCESS (code=1, address=0x100000000)`

The ktx2 files were generated using toktx, built from the branch with the command `toktx --bcmp --t2 trout.ktx2 trout.jpg`. 

[branch](https://github.com/daverin/KTX-Software/tree/cmake_unity_basisu) 
[trout.ktx2](https://github.com/atteneder/KtxUnity/files/5184891/trout.ktx2.zip)

**Comment by atteneder** [comment]
Please Update KtxUnity. It should be solved now (with up-to-date ktx2 files)
