### ISSUE TITLE
WebGL Build Error - Plugins Colliding With Each Other

### ISSUE THREAD

**Issue by DerrickBarra** [atteneder/KtxUnity#17]
**Reported With Unity Version:** 2020.1.4f1

**Issue:** When making a WebGL build, two .dll files collide, causing the build to fail.

`Plugin 'ktx_unity.dll' is used from several locations:
 Packages/com.atteneder.ktx/Runtime/Plugins/x86_64/ktx_unity.dll would be copied to <PluginPath>/ktx_unity.dll
 Packages/com.atteneder.ktx/Runtime/Plugins/x86/ktx_unity.dll would be copied to <PluginPath>/ktx_unity.dll
Please fix plugin settings and try again`

**How To Recreate:** 
- Add the KtxUnity plugin to a blank Unity project using Package Manager.
- Switch to WebGL build target and build. 

Bug occurs in a blank project with just the KtxUnity plugin or even in the KtxUnity demo git repo.

**Comment by atteneder** [comment]
Hi @DerrickBarra,

Thanks for reporting!

This is strange. The DLLs are not required for building WebGL at all (the `libktx_unity.bc` is used). Might be a Unity bug. Unfortunately those happen to appear with the package manager sometimes. For me re-importing the whole project and restarting Unity helps (sometimes).

I'll be updating the native libs very soon and then I'll try to reproduce your steps.

Thanks,
Andi

**Comment by sybixsus** [comment]
I can confirm that I've had this bug too and it does appear to be caused by the package manager. I removed the package, grabbed the repo manually via Git, and then copied the folders into the project manually and it has not happened again since then.

Might it be that the Editor loads one of the Windows DLLs when you're using play mode in the editor? And then when you go to build, it's still loaded?

**Comment by DerrickBarra** [comment]
@sybixsus @atteneder When I remove KtxUnity from the package manager, and then import it as a standard plugin, I'm getting a different error.

![image](https://user-images.githubusercontent.com/20777145/96345316-6f9aef00-1068-11eb-8ae8-39d3a15887ba.png)

Reimporting all of my assets still shows the same issue with ktx_unity.dll. 

@atteneder I'll try this in a completely blank project and see if the same thing occurs, and if you need I can open up a new Jira issue. I'm not entirely sure this new bug is related to the original one I reported.

**Comment by sybixsus** [comment]
@DerrickBarra Apologies that my suggestion has proven unhelpful. That particular plugin in the inspector looks identical for me as it does for you. I think the only difference (as far as I can see) is that I copied the entire "runtime" folder into the project as is. But I don't see why that would make any difference.

**Comment by DerrickBarra** [comment]
@atteneder @sybixsus What Unity version are you testing with? At this point, I've tested the following using the current stable version of KtxUnity (master branch).

**Test 1**
Create a blank Unity project in 2020.1.4f1. [Add KtxUnity via the package manager.](https://drive.google.com/file/d/1FT6EeHcIVgpqQgFiMGA6-LbAVib0F8sc/view?usp=sharing)
- ktx_unity.dll is used in several locations (.../x86/ktx_unity.dll and .../x86_64/ktx_unity.dll)
- Unable to test any further due to compiler errors

**Test 2**
Create a blank Unity project in 2020.1.4f1. [Add KtxUnity via the assets folder.](https://drive.google.com/file/d/1sB6ajzb_Ci2PA1-rXANyNHJ8_jMPD_6d/view?usp=sharing)
- Failed to load 'Assets/KtxUnity-master/Runtime/Plugins/x86_64/ktx_unity.dll', expected x64 architecture, but was Unknown architecture. You must recompile your plugin for x64 architecture. 
- Prevents me from using KtxUnity scripts or making builds.

**Test 3**
Create a blank Unity project in 2020.1.4f1. Add KtxUnity via the assets folder. Remove the Plugins/x86 and Plugins/x86_64 folder and make a WebGL build.
- This prevents the ktx_unity.dll bug in Test 2.
- Build succeeds in the default sample scene!

**Test 4**
Same as Test 3, but try adding a TextureUrlLoader.cs component to a UI Image, so we can test loading a .basis file in a WebGL build.
- Can't add script component 'TextureUrlLoader' because the script class cannot be found. Make sure there are no compile errors and that the file name and class name match. [(screenshot)](https://drive.google.com/file/d/1edL3UCOott606-6r-YnC7z5DUvwoGT9a/view?usp=sharing)
- Force rebuilt the asset database and tried again with the same error

And that's about as far as I can get in my testing of KtxUnity outside of working within the KtxDemo repo (which can't build to WebGL due to the windows dll name conflict errors).

Any ideas on other things I can try?

**Comment by atteneder** [comment]
Testing on macOS only so far. You have to use the [ktx_4.0.0_beta_4](https://github.com/atteneder/KtxUnity/tree/ktx_4.0.0_beta_4) branch and download and copy the native libs from the latest [CI builds](https://github.com/atteneder/KTX-Software-Unity/actions).

It's not really straight forward to test this half-ready state, but feel free to ask questions if you really want to test the bleeding-edge version.

That beinig said, I'm working hard to get the remaining native libs to build (Android mainly). After that a next beta release is likely to come soon (if you have the patience)

**Comment by atteneder** [comment]
Once the libs are ready, I'll test in 2020.1 as well and see if I run into similar problems.

**Comment by DerrickBarra** [comment]
@atteneder Thanks, I'm going to try the same test on a 2019 LTS version of Unity and I'll let you know.

**Comment by DerrickBarra** [comment]
@atteneder So I made a new blank 2019.4.12f1 LTS Unity project and grabbed the latest stable KtxUnity from the package manager. When making a WebGL build I still get the [ktx_unity.dll plugin in multiple locations bug](https://drive.google.com/file/d/181VOv2pQ1aPtbAxNjj0_MaE8YFlavz3x/view?usp=sharing).

And when attempting to load a .basis file (my standard test) in the editor, I get an [EntryPointNotFoundException](https://drive.google.com/file/d/1TrdNdF18TuDDy0YW6TjYuCZamNEbXcHW/view?usp=sharing). This occurs even after reimporting all of the assets in this empty demo project.

**Comment by atteneder** [comment]
> @atteneder So using the latest beta with the new binaries, I'm no longer getting the "ktx_unity.dll plugin in multiple locations" bug, which is great!
> 
> EDIT: Once I modified my binaries to the appropriate settings per binary, I was able to successfully make WebGL and Android builds! Unity Editor doesn't work yet (EntryPointNotFound bug still), but I believe that's because the x86_x64 binaries still need to be updated correct?

yes!
will commit binaries today (cannot wait longer myself). it should be easy then.

**Comment by atteneder** [comment]
I've released Update 0.8.0. It should have the correct settings on the libraries.

Reopen if there's still issues.

Thanks!
