### ISSUE TITLE
.ktx2 with .basis payload support?

### ISSUE THREAD

**Issue by DerrickBarra** [atteneder/KtxUnity#25]
Quick question @atteneder , I know KtxUnity supports the .ktx and .basis formats, but does it support a .basis payload inside of a .ktx2 container?

**Comment by DerrickBarra** [comment]
I know throughout this repo you mention supporting KTX 2.0, but I haven't seen mention if you explicitly support the .ktx2 container. I'll eventually test this on my own, but if you could just give me a sanity check, that would help!

**Comment by atteneder** [comment]
Hi!

I must have missed your initial question, sorry about that.

Yes, it supports KTX version 2.0 (and 2.0 only). It also supports basis supercompression in KTX 2.0 files (ETC1s and UASTC mode, but no other format like uncompressed).

Did you have any trouble?

hth

**Comment by DerrickBarra** [comment]
Haven't actually tested them yet, but one of the tools we use optimizes models into glb format with .ktx2 container formatted basis textures. I was familiar with .ktx and .basis, but having a .ktx2 file surprised me. 

I was commenting that this repo doesnt mention files with .ktx2 file extensions, only .ktx. I wasnt aware until I looked it up that the KTX2 format used the .ktx2 file extension.

Once I test the file I will close this thread if it loads without issue.

**Comment by atteneder** [comment]
I see. It's confusing since I used the `.ktx` extension for KTX 2 files as well. I should mention it in the README.

**Comment by atteneder** [comment]
updated readme
