### ISSUE TITLE
Sprite Flipping & Sizing Issue when Preserve Aspect Ratio is enabled

### ISSUE THREAD

**Issue by DerrickBarra** [atteneder/KtxUnity#28]
Quick question @atteneder , can you test this [.basis file](https://bxrtest.s3.amazonaws.com/KTX+Tests/mario_transparent.basis) loaded as a sprite with your sprite flipping logic and let me know what you see? I'm expecting it to match this [png version](https://bxrtest.s3.amazonaws.com/KTX+Tests/mario_transparent.png), but the results I'm seeing are a bit strange ([flipped horizontally, larger scale](https://drive.google.com/file/d/1ymaTnbwd7HuumyRRQwLkoCfojve4GjBn/view?usp=sharing)).

If I force the IsXFlipped attribute to true, the basis sprite is the same size as the .png loaded version on the right, but is still not flipped on the horizontal (not facing the right).

**Comment by atteneder** [comment]
Hi @DerrickBarra 

I tried loading with KtxUnity 0.9.0 and [this script](https://github.com/atteneder/KtxUnityDemo/blob/main/Assets/Scripts/BasisImageLoader.cs).

I looked identical to the PNG put on an Image component (mario facing right). Maybe look at my script and compare to yours.

hth

**Comment by DerrickBarra** [comment]
@atteneder Sorry for the weekend delay. So my original code was a modified version of your Image Sprite loading logic, but just in case I copied the logic over to what is basically a duplicate of the same class you linked to (just with some KTX define symbol checks), and the sprite is still loading on my Windows PC flipped and larger than the .png version.

Are you testing on a Mac? I'm going to make an Android or WebGL build next to see if the flipping works differently on those exports. Don't know why it would, but it can't hurt to elimiate those possibilities.

**Comment by DerrickBarra** [comment]
@atteneder So I ran another test with new .basis files just to confirm the bug can be recreated.

[Mario NoFlip](https://bxrtest.s3.amazonaws.com/KTX+Tests/mario_noflip.basis) [default basisU configuration, no flip]

![mario_noflip](https://user-images.githubusercontent.com/20777145/98702742-c4b8e080-2348-11eb-92d9-9aea15cb50ae.PNG)

[Mario yflip](https://bxrtest.s3.amazonaws.com/KTX+Tests/mario_yflip.basis) [-yflip command added to basisU]

![mario_yflip](https://user-images.githubusercontent.com/20777145/98702669-ae128980-2348-11eb-8a6e-dad783cab70d.PNG)

**Comment by DerrickBarra** [comment]
@atteneder Hey bud, anything you want me to try on this bug?

**Comment by atteneder** [comment]
@DerrickBarra The script counter-acts the flipping by setting negative size values on the Sprite. Those negative values confuse the `Image` component (or break its Sprite placement calculations) and I couldn't find any other ordinary way of teaching either `Sprite` or `Image` to simply flip it.

You have to bite the dust and do the RectTransform position calculations yourself. Here's a simple example (to be added at the end of `ApplyTexture`);

```csharp
float scale = 0.5f; // Set this to whatever size you need it - best make it a serialized class field
var rt = GetComponent<RectTransform>();
rt.sizeDelta = new Vector2(texture.width*scale, texture.height*scale);
```

hth

**Comment by DerrickBarra** [comment]
@atteneder I recommend the documentation make note of this incompatibility with the Unity Image preserveAspect attribute. You can point to the possible solutions (pre-flipping your textures, or as a backup modifying the rectTransform to deal with the scaling.)

For our team's use, it'll be best to just pre-flip the textures in basisu or toktx to ensure we don't need to deal with the changes to our UI prefab hierarchies. Thanks!
