### ISSUE TITLE
[Request] Method style transcoder.

### ISSUE THREAD

**Issue by gtk2k** [atteneder/KtxUnity#32]
I want a method style transcoder like this.
```C#
var loader = new BasisUniversalLoader();
var tex = loader.loadFromUrl(url);
material.mainTexture = tex;
```

**Comment by atteneder** [comment]
Working on a new async API. It'll look like this:

```csharp
async Task LoadFromUrl() {
    var loader = new BasisUniversalLoader();
    var result = await loader.LoadFromUrl(url);
    material.mainTexture = result.texture;
    Debug.Log(result.orientation); // Also contains orientation info
}
```

Similar complexity/boilerplate code, no fiddling with callbacks, but still async.

I don't know how to make it sync, but I also don't see any reason one would want that.

Any objections?

**Comment by gtk2k** [comment]
Oh!
Yes!
My request was incorrect.
Asynchronous is okay.
No synchronization required!
