### ISSUE TITLE
KTX BASIS textures fail to load in IOS builds

### ISSUE THREAD

**Issue by ASquareDevs** [atteneder/KtxUnity#33]
Hi, I'm Jose with A Square, my team is working with BrandXR on the Discovery platform.

I am having issues building to iPhone where I get this issue only in builds, in editor for IOS the ktx and basis textures are loaded and it works, but when I try to build I'm getting this error and the onTextureLoaded action is never called.

I'm getting this in XCode's debug console;
![image](https://user-images.githubusercontent.com/69996525/105189635-2ba20500-5b03-11eb-9d1c-e0df39ded146.png)

These are the textures I am trying to load:
https://bxrtest.s3.amazonaws.com/KTX+Tests/horse/material0_basecolor.ktx2
https://bxrtest.s3.amazonaws.com/KTX+Tests/mario_transparent.basis

**Comment by atteneder** [comment]
Thanks for reporting. I'll try to reproduce soon.

**Comment by atteneder** [comment]
I could reproduce! Will look at it next week.

**Comment by ASquareDevs** [comment]
I did manage to fix it by setting Xcode's optimization level to smallest when it was set to smallest and fastest. That and the Allocation of the native array had to be set to temp job.

**Comment by atteneder** [comment]
Great observation! But weird...makes me think it's some imprecision only showing up in certain configurations (architecture-optimization level combination)

**Comment by blackbird-91** [comment]
@atteneder I'm having a similar issue with crashes on iOS builds with ktx2 files. It works fine in the editor and on iOS build only when deep profiling is enabled in build settings. 
When trying to create a release build or one without deep profiling enabled, it crashes when trying to load an object with ktx2 texture. 

The above suggestion to set the optimization level to smallest did not work in my case.

Unity version: 2020.2.7f1
GLTFast version: 3.0.2
KTXUnity version: 1.0.0
Device tested: iPhone 11 running 13.2.3
![Screen Shot 2021-03-10 at 12 45 47 AM](https://user-images.githubusercontent.com/39198232/110525082-314abd00-813a-11eb-9425-d96cc42c293a.png)

**Comment by atteneder** [comment]
@blackbird-91 Thanks for reporting.

Might be related to #11 on Android. I'll try to have a look soon.

**Comment by blackbird-91** [comment]
> @blackbird-91 Thanks for reporting.
> 
> Might be related to #11 on Android. I'll try to have a look soon.

@atteneder Thanks for following up and directing me to the issue. Based on the thread you linked, a previous version of both gltfast and KTXUnity where you use coroutines instead of async await should technically work in the iOS release builds. But that did not fix the issue for me, I tried going back upto gltfast version 1.0.1 and ktxunity v0.8. All of them crashed.

Some more specs I missed in my previous post -
15" Macbook Pro (2016)
OSX version: Big Sur 11.1
XCode version: 12.4(12D4e)

Please let me know if you got any updates regarding this issue.

**Comment by ruben-ivre** [comment]
Any news on this issue? we tried everything we could but we can't get it working with the sample project. We tried the XCode optimization and the allocation fix, but no luck. We tried with latest version here and with the forked version from @mmusial too, which fixed Android for us.

**Comment by mmusial** [comment]
> Any news on this issue? we tried everything we could but we can't get it working with the sample project. We tried the XCode optimization and the allocation fix, but no luck. We tried with latest version here and with the forked version from @mmusial too, which fixed Android for us.

For me using my "coroutine branch" (details: #11) resolved all crashing on both Android and iOS. I'm using ETC1S (RGB) and UASTC (RGB/RGBA). What type of texture you are trying to load?

**Comment by atteneder** [comment]
Sorry about the inconvenience, but unfortunately no. It'll take some more weeks for me to have a look since I'm on paternity leave as well.

**Comment by ruben-ivre** [comment]
> For me using my "coroutine branch" (details: #11) resolved all crashing on both Android and iOS. I'm using ETC1S (RGB) and UASTC (RGB/RGBA), both as KTX2 files. What type of texture you are trying to load?

We tried with your branch too, as we use it to solve our Android issues, but iOS is still failing. We are using lz compressed BASIS format in KTX container (we use the ktxtool with --bcmp flag).

**Comment by mmusial** [comment]
> > For me using my "coroutine branch" (details: #11) resolved all crashing on both Android and iOS. I'm using ETC1S (RGB) and UASTC (RGB/RGBA), both as KTX2 files. What type of texture you are trying to load?
> 
> We tried with your branch too, as we use it to solve our Android issues, but iOS is still failing. We are using lz compressed BASIS format in KTX container (we use the ktxtool with --bcmp flag).

Below are my arguments for `toktx` that works for me (Android, iOS, PC[Win64]):
```
toktx --srgb --lower_left_maps_to_s0t0 --genmipmap --bcmp --clevel 3
toktx --srgb --lower_left_maps_to_s0t0 --genmipmap --uastc 3 --zcmp 10
```

**Comment by Dover8** [comment]
Adding another one to the iOS Runtime Crash crew. Our sample runs fine when using Deep Profiling mode, but none of the solutions get us to a stable release version.

**Comment by ruben-ivre** [comment]
Thank you very much @mmusial, adding the --genmipmap parameter did the trick, I owe you twice, one for the Android fix and another for this one.
Adding the mipmaps makes the file a little bit bigger, but we can live with that.

**Comment by mmusial** [comment]
> Thank you very much @mmusial, adding the --genmipmap parameter did the trick, I owe you twice, one for the Android fix and another for this one.
> Adding the mipmaps makes the file a little bit bigger, but we can live with that.

I'm glad I could help :)

**Comment by atteneder** [comment]
I found two bugs in the C binding that are likely the real reason for those crashes. I just tested KtxUnity 1.1.0 successfully on iOS (arm64).
