### ISSUE TITLE
Tiling/offset data is not correct

### ISSUE THREAD

**Issue by M4kHack** [atteneder/KtxUnity#34]
Hi Atteneder,

I'm loading glasses and the texture on the lenses does not render correctly.
Is it a unity setting? Something wrong with the texture compression? something els?

Everything works fine if I load it in https://gltf-viewer.donmccurdy.com/

If you have any idéa let me know=)

![LensIssue](https://user-images.githubusercontent.com/78788078/109782591-55257480-7c09-11eb-9dc4-ea6a1a1d8eb1.png)

//M4k

**Comment by M4kHack** [comment]
Update:
It seems to be a tiling issue, I can manually adjust it in the editor, but I should not have to do this?

![Tiling](https://user-images.githubusercontent.com/78788078/109784499-6cfdf800-7c0b-11eb-88a7-f6e8376cdfd2.png)

**Comment by atteneder** [comment]
Hi,

KtxUnity just provides a Texture2D plus orientation information. What you do with it (and how it is applied correctly) is up to other levels of your logic.

If you use this in the context of glTF (like loading with glTFast), then the question is, why is the correct tiling/offset not applied  by the glTF library. In that case it's again not an issue of KtxUnity.

Feel free to re-open if I missed something or you disagree.
