### ISSUE TITLE
KTX Basis textures fail to load in editor in Unity 2021.1.0f1 & 2021.2.0a10.1508

### ISSUE THREAD

**Issue by DerrickBarra** [atteneder/KtxUnity#36]
Hey again @atteneder, making sure you have plenty of bugs to work on when you get back :)

So in Unity 2021.1.0f1 (the latest stable version from the Unity Hub at the time of this post), .basis textures fail to load in the Editor when loading with KTXUnity 1.0.

![image](https://user-images.githubusercontent.com/20777145/113037217-2ac0cb80-9163-11eb-9a3d-df1a49754cf6.png)

You can see in the image above, I'm using the [KTXUnity-Tester github](https://github.com/BrandXR/KTXUnity-Tester), and upgraded it to 2021.1.0f1 on my local instance for testing.

After that I just press the play button on the testing scene to encounter the error.

**Comment by DerrickBarra** [comment]
Oh, and just tried it on Unity 2021.2.0a10.1508, which was the latest alpha from Unity hub today. The same error exists for KTXUnity in the editor.

![image](https://user-images.githubusercontent.com/20777145/113040220-90628700-9166-11eb-9b6c-052ed6dc34c2.png)

**Comment by DerrickBarra** [comment]
So turns out this bug was due to a change in how UnityWebRequests work in 2021.1.0f1. The script in the test repo will try to cache the .basis bytes via a WebRequest downloadHandler.data. However that is now null in the newest Unity releases so it can't be used for caching. When this caching logic is commented out, the .basis files load fine, so clearly it's not an issue with KTXUnity.

![image](https://user-images.githubusercontent.com/20777145/113055950-2c958980-9179-11eb-8e61-30d400e2b557.png)

**Comment by atteneder** [comment]
Sorry for the late reply.

Great that you found the problem. Might be useful to know for the future.

Thanks!
