### ISSUE TITLE
iOS libraries should be built with bitcode embedded

### ISSUE THREAD

**Issue by push-pop** [atteneder/KtxUnity#37]
Unity sets bitcode enabled by default. Since iOS binaries were not built with embedded bitcode, it requires turning off this setting manually or with a build postprocess in order to make an iOS build.

Would be great if we could have iOS binaries that have bitcode enabled so builds work with default settings. 

Some info on benefits of Bitcode and why it's default in Unity: 
https://support.unity.com/hc/en-us/articles/209933103

How to build with Bitcode:
https://stackoverflow.com/questions/31233395/ios-library-to-bitcode

**Comment by atteneder** [comment]
Hi @push-pop ,

Thanks for reaching out. I've done checks/tests and I think I can make bitcode work soonish.

**Comment by cvetelinast** [comment]
Hi, I have the same issue, any progress on this? The related issue seems to be closed, but this one is still open.

**Comment by atteneder** [comment]
Yes, it's actually not hard to add them, but I wanted to fix 2021.2 beta WebGL and Apple Silicon first. If I'm not making progress this week, I'll postpone those fixes and add bitcode first.

**Comment by lhadzhipopov** [comment]
Experiencing the same issue. Would really appreciate a fix. Thank you!

**Comment by atteneder** [comment]
Hi @lhadzhipopov ,

which version of KtxUnity are you using and how exaclty did you prove/certify that bitcode is missing?

I'm asking because this issue was supposedly fixed in KtxUnit 1.1.0 (which includes binaries from KTX-Software-Unity 0.4.1 where bitcode was added in [0.4.0](https://github.com/atteneder/KTX-Software-Unity/releases/tag/v0.4.0)). I just forgot to close this issue and now I'm confused why you're experiencing problems.

Regards,
Andreas

**Comment by daverin** [comment]
Hi @atteneder 

Also finding that 1.1.0 wasn't built with bitcode. 

Xcode build logs (from Fastlane):

<img width="1038" alt="Screenshot 2021-07-16 at 19 11 25" src="https://user-images.githubusercontent.com/70378377/125984544-379e8dbd-6d3b-4580-bdbb-3b16b118dc39.png">

**Comment by atteneder** [comment]
@daverin Thanks for the report. I'll look into it

**Comment by atteneder** [comment]
Sorry for the wait and the confusion.

It should be fixed now in KtxUnity 1.1.1 (live anytime soon now)

Re-open the issue if you still have problems.

Thanks!
