### ISSUE TITLE
Native Lib Source

### ISSUE THREAD

**Issue by onehundredfeet** [atteneder/KtxUnity#44]
Hi,

I can't seem to find the native library source. Is it somewhere in this repo? or another one?

Thanks!

Cheers,
Ryan.

**Comment by atteneder** [comment]
This is the repository the binaries are built with:

https://github.com/atteneder/KTX-Software-Unity

This is the most recent GH action build:

https://github.com/atteneder/KTX-Software-Unity/actions/runs/1038829625

Regards,
Andi
