### ISSUE TITLE
ktx_unity.dll', expected x64 architecture, but was Unknown architecture. You must recompile your plugin for x64 architecture.

### ISSUE THREAD

**Issue by friuns2** [atteneder/KtxUnity#58]
![image](https://user-images.githubusercontent.com/16543239/171314333-92f0456f-17c4-4cc7-a998-dd01f6f25355.png)  
downloaded dlls from release are they corrupted?  
  
Unity 2019.4

**Comment by friuns2** [comment]
ah its lfs

**Comment by triansion** [comment]
I also have the same problem, how to solve this

**Comment by friuns2** [comment]
check dll size, if its empty it didn't downloaded properly
