### ISSUE TITLE
Unable to Load ktx2 textures at run time in unity iOS editor

### ISSUE THREAD

**Issue by hggz** [atteneder/KtxUnity#62]
Hey all, I'm trying to load my ktx2 textures using the async samples provided, from within the Unity Editor which is set to use the iOS player. Every time I do those it fails with an exception:
`EntryPointNotFound`
Is this not possible? Should I be using another configuration? The assemblies for ktunity and ktunity.editor are added.
I'm on unity 2019.3.1 also. Thanks!

**Comment by hggz** [comment]
> Hi @hggz ,
> 
> Are you using this project (KtxUnityDemo) actually?
> 
> How exactly did you install the KtxUnity package?

I used the installer package which added a scoped repository and then imported the package from there. All the symbols worked / compiled but when it came time to run the editor with the iOS player set as the build target, it kept giving me the `EntryPointNotFound` exception following the same methodology in the demo

**Comment by atteneder** [comment]
Could not reproduce with Unity 2021.3.4 and KtxUnity 2.1.2.
Trying 2019.4.40 now

**Comment by atteneder** [comment]
Also works with 2019.4.40 and KtxUnity 1.2.3.

Usually this error appears when folks install the package via GIT URL and don't use GIT LFS. Please make sure that it is installed correctly, re-test and provide more info (maybe a test project) in case it still does not work.
