### ISSUE TITLE
ScriptedImporter textures always display as opaque

### ISSUE THREAD

**Issue by hybridherbst** [atteneder/KtxUnity#64]
The regular texture importer is able to show textures as opaque or transparent based on the "alphaIsTransparency" option; however, it seems that textures are always displayed as opaque (with separately selectable A channel) in the KtxImporter textures.

__RGB | A__
![image](https://user-images.githubusercontent.com/2693840/184129309-92343e97-1921-42b8-94d2-371a3a119e79.png) ![image](https://user-images.githubusercontent.com/2693840/184129333-5d42d4f5-b088-4d59-8993-dac9fa236d5c.png)

__Regular texture importer for same file shows transparency__
![image](https://user-images.githubusercontent.com/2693840/184129487-50304e28-aa7e-4ff2-950d-98aadefe37b2.png)

**Comment by atteneder** [comment]
Thanks for reporting!

Good news: Doing this in `KtxImporter.OnImportAsset` seems to bring the checkerboard background.

```csharp
result.texture.alphaIsTransparency = true;
```

On regluar TextureImporters this would not only show the checkerboard/alpha blending, but enable some color filtering (see [details](https://docs.unity3d.com/ScriptReference/TextureImporter-alphaIsTransparency.html)), but I assume it does not apply here.

So I assume this does no harm and I'd simply go with this solution.

Or do you think there has to be a dedicated checkbox in the settings?

**Comment by hybridherbst** [comment]
Oh, great if that's all that's needed :)
