### ISSUE TITLE
can not use in android x86?

### ISSUE THREAD

**Issue by iamnewaplayer** [atteneder/KtxUnity#71]
i get a log
Unable to load DLL 'ktx_unity'. Tried the load the follwing dynamic libraries:Unable to load dynamic library 'ktx_unity' because of 'Failed to open the requested dynamic lib'

**Comment by atteneder** [comment]
Hi,

Thanks for reporting. x86 binaries are not included in this package. IIRC the reason was that there aren't many devices with that architecture. What's your use case?

**Comment by iamnewaplayer** [comment]
just test

**Comment by iamnewaplayer** [comment]
i hava a z8550 android pad can not run my app with ktxunity

**Comment by atteneder** [comment]
The decision to ditch Android x86 was based on [this answer](https://android.stackexchange.com/a/186348), IIRC. Sorry to tell you I won't change that.

What you can do though is compile the native library yourself. The [source](https://github.com/atteneder/KTX-Software-Unity/) is available and  the Android specific CMake configuration I used can be read in its [GitHub action workflow](https://github.com/atteneder/KTX-Software-Unity/blob/1669653fdca908dfe7e0641b71b0412415b3298a/.github/workflows/main.yml#L179).

Thanks for your understanding.
