### ISSUE TITLE
Macbook pro m1 pro Unknown format, not a static library!

### ISSUE THREAD

**Issue by Ra1n18** [atteneder/KtxUnity#74]
Building Library/Bee/artifacts/WebGL/build/debug_WebGL_wasm/build.js failed with output:
emcc: error: Library/PackageCache/com.atteneder.ktx@a3d6d62eea/Runtime/Plugins/WebGL/libktx_unity.a: Unknown format, not a static library!
I tried on PC and macbook pro 2019 they are building just fine

**Comment by atteneder** [comment]
KtxUnity version?
How did you install it (from what source)?
Unity version?

**Comment by Ra1n18** [comment]
If you cloned it from GitHub (or downloaded a ZIP), make sure the binaries are properly fetched (since they are GIT LFS files). this answer helps me 
unity version  2022.1.23f1

**Comment by Ra1n18** [comment]
I have done it with openupm and it fixed my problem
