### ISSUE TITLE
win7 64 dx11 can't Load ktx_unity.dll

### ISSUE THREAD

**Issue by iamnewaplayer** [atteneder/KtxUnity#75]
win7 64 dx11 can't Load ktx_unity.dll

**Comment by iamnewaplayer** [comment]
It has nothing to do with the system
win7 win10 win11 also has some player can't load ktx_unity.dll

**Comment by iamnewaplayer** [comment]
unable to load DLL 'ktx_unity'. Tried the load the following dynamic libraries: Unable to load dynamic library "ktx_unity" because of 'Failed to open the requested dynamic library (0x06000000)' - 找不到指定的模块. (WinError:0000007e)

**Comment by atteneder** [comment]
This might be similar to an [issue](https://github.com/atteneder/DracoUnity/issues/65) that's been reported for DracoUnity.

The issue might get resolved by installing [Microsoft Visual C++ Redistributable packages for Visual Studio 2015, 2017, 2019, and 2022](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022). Could you please try that and report if it worked?

Thanks!

**Comment by atteneder** [comment]
I assume that solution works. Re-open if that's not the case.
