### ISSUE TITLE
Installer package error

### ISSUE THREAD

**Issue by Daniel4144** [atteneder/KtxUnity#76]
Trying to install the package through the unitypackage file does not work.

Steps to reproduce:
- Install glTFast and Draco packages with installer unitypackages
- -> Packages are installed correctly
- Install this package with installer unitypackage
- ->Package is not installed

The manifest.json is broken with this incomplete scoped registry entry:
{
      "name" : "Atteneder",
      "url" : "https://package.openupm.com",
      "scopes" : [
      ]
}

Errors in the console:
- [Manifest Tools] The scope com.atteneder from https://package.openupm.com already exists in the manifest. It won't be added again. Please make sure you're getting the package from the right place!
UnityEngine.Debug:LogWarning (object)
- [Package Manager Window] Cannot perform upm operation: Registry configuration is invalid:
  Scoped registry at position 2 is invalid:
    "scopedRegistries[1].scopes" must contain at least 1 items [InvalidParameter].
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()
- [Package Manager Window] Error fetching package list offline.
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()
- Failed to resolve packages: Registry configuration is invalid:
  Scoped registry at position 2 is invalid:
    "scopedRegistries[1].scopes" must contain at least 1 items. No packages loaded.
- [Package Manager Window] Cannot perform upm operation: Registry configuration is invalid:
  Scoped registry at position 2 is invalid:
    "scopedRegistries[1].scopes" must contain at least 1 items [InvalidParameter].
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()
- UnityEditor.PackageManager.UI.Internal.UIError
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()

Installing the package by manually adding the dependency to the manifest file works:
"com.atteneder.ktx": "2.2.3"

**Comment by atteneder** [comment]
Hi @Daniel4144,

Thanks for reporting this one. I suspect that the error is due to inconsistent naming of the scoped registry entry. I tried to reproduce with Unity 2021.3.15f1, but it did work there. Nonetheless I changed the naming. Could you try it again and tell me if it works now?

Thanks!

**Comment by Daniel4144** [comment]
Hi @atteneder 
I tried it again with a new empty project and now it worked.
(I tested with Unity 2021.3.11f1)
