### ISSUE TITLE
Why doesn't some PNG files 32 bit with alpha channel convert to ktx2?

### ISSUE THREAD

**Issue by JunSourceX** [atteneder/KtxUnity#78]
Why doesn't some PNG files 32 bit with alpha channel convert to ktx2?

**Comment by atteneder** [comment]
I don't understand the question.

This package loads KTX 2.0 textures. If you want to create KTX files, you can use other tools like the `toktx` CLI tool that comes with [KTX-Software](https://github.com/KhronosGroup/KTX-Software).

Encoding from within the Editor would be a feature, but no plans for such.

**Comment by JunSourceX** [comment]
> I don't understand the question.
> 
> This package loads KTX 2.0 textures. If you want to create KTX files, you can use other tools like the `toktx` CLI tool that comes with [KTX-Software](https://github.com/KhronosGroup/KTX-Software).
> 
> Encoding from within the Editor would be a feature, but no plans for such.

oh, sorry, I accidentally created a question for you, I wanted to go to KTX-Software)

**Comment by atteneder** [comment]
No worries
