### ISSUE TITLE
Question for texture ktx compressed so many has artifacts

### ISSUE THREAD

**Issue by johnnyapu15** [atteneder/KtxUnity#80]
Hi,
This is the screen seen in the model-viewer after ktx compression and the screen opened in unity using ktxUnity.
In Unity, there are artifacts like spots.
Why would there be such a difference?
I used toktx for compressing, the command are same as below.

`toktx --genmipmap --uastc 3 --uastc_rdo_l 0.5 --uastc_rdo_b 100 --zcmp 20 --assign_oetf linear --assign_primaries none --resize 2048x2048 --threads 10`

![image](https://user-images.githubusercontent.com/16520778/215782881-0a38e293-ee0e-4103-8e91-75d17ab2d8ef.png)

![image](https://user-images.githubusercontent.com/16520778/215782927-a9012a97-44f1-44bc-96f6-a32c90fdb1c8.png)

Thanks.

**Comment by MAG-AdrianMeredith** [comment]
I'd also like an answer to this, been struggling to get high quality compression.  Is there any recommended settings e.g. high,medium, low?

**Comment by atteneder** [comment]
Hi,

I haven't played a lot with the settings, but the defaults (UASTC) usually gives me good results.

Just to clarify, does the result look similar in other viewers/engines? I want to rule out that this is a bug of KTX for Unity.

thanks

**Comment by MAG-AdrianMeredith** [comment]
I totally forgot about this one, too late now.  But in short I'm using playcanvas and compressing normals with uastc produces the artifacts (noticeable macro blocking) like on the second screenshot.  We therefore don't compress them as the quality is basically unusable (cept for low lod levels).

**Comment by MAG-AdrianMeredith** [comment]
So probably not a unity bug yes

**Comment by atteneder** [comment]
Can you provide a sample texture? Ideally the original plus your `ktx`/`toktx` settings.

If yes, please re-open so we can keep track and I'll look into it.
