### ISSUE TITLE
how to asynchronously load textures within the update() function?

### ISSUE THREAD

**Issue by iamnewaplayer** [atteneder/KtxUnity#84]
how to asynchronously load textures within the update() function?
i used await in update(); but it is also not blocking update thread

**Comment by atteneder** [comment]
Hi @iamnewaplayer ,

Have a look at the [KTX for Unity documentation](https://docs.unity3d.com/Packages/com.unity.cloud.ktx@3.2/manual/how-to.html#loading-textures).

Note that it refers to the successor of this package, which I recommend you to switch to.
